# Change these first
owner: nbitzz # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: fyle.uk
    url: https://fyle.uk
  - name: fyle.uk beta
    url: https://beta.fyle.uk

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fyle.uk
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/nbitzz/monofile/1.3.0/assets/icons/icon_temp.svg
  name: fyle.uk
  introTitle: "**monofile** @ fyle.uk"
  introMessage: The open source, Discord-based file sharing service
  navbar:
    - title: Stable
      href: https://fyle.uk
    - title: Beta
      href: https://beta.fyle.uk
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
