# Change these first
owner: nbitzz # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Site
    url: https://fyle.uk
    maxResponseTime: 1200
  - name: Basic API
    url: https://fyle.uk/server
    icon: https://monofile.glitch.me/file/23233072126561183
    maxResponseTime: 1200
  - name: File access
    url: https://fyle.uk/file/fish
    maxResponseTime: 2000
  - name: Site (beta)
    url: https://beta.fyle.uk
  - name: File access (beta)
    url: https://beta.fyle.uk/file/fish
    maxResponseTime: 2000
  - name: coolviruses.download Firefish
    url: https://coolviruses.download/
    maxResponseTime: 2000
  - name: fedi.fnaf.stream
    url: https://helloeverybodymynameismarkiplierandwelcometofivenightsatfreddys.anindiehorrorgamethatyouguyssuggestedenmasseandisawthatyamimash.playeditandhesaidthatitwasreallyreallygoodsoimveryeagertoseewha.tisupandthatisaterrifyinganimatronicbear.fnaf.stream/
    maxResponseTime: 3000
  - name: Sshwifty
    url: https://ssh.fyle.uk/
    maxResponseTime: 1000
  - name: Bore
    check: "tcp-ping"
    url: tunnel.fyle.uk
    port: 7835
  - name: theUnfunny
    url: https://unfunny.glitch.me/
    maxResponseTime: 1000
  - name: Jellyfin
    url: https://jelly.fyle.uk/
  - name: "split's computer (lol)"
    url: https://me.fyle.uk/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fyle.uk
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/nbitzz/monofile/1.3.0/assets/icons/icon_temp.svg
  # grrrr.... upptime....
  themeUrl: https://monofile.glitch.me/file/26945874646066836
  name: fyle.uk
  introTitle: "fyle.uk"
  introMessage: The open source, Discord-based file sharing service *(and a few other things)*
  navbar:
    - title: Stable
      href: https://fyle.uk
    - title: Beta
      href: https://beta.fyle.uk
    - title: Mastodon
      href: https://so.fyle.uk

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
