# Change these first
owner: nbitzz # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Site
    url: https://fyle.uk
    maxResponseTime: 1200
  - name: Basic API
    url: https://fyle.uk/server
    icon: https://fyle.uk/file/23233072126561183
    maxResponseTime: 1200
  - name: File access
    url: https://fyle.uk/file/fish
    maxResponseTime: 2000
  - name: Mastodon server
    url: https://so.fyle.uk/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fyle.uk
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/nbitzz/monofile/1.3.0/assets/icons/icon_temp.svg
  # grrrr.... upptime....
  themeUrl: https://status.fyle.uk/macchiato.css
  name: fyle.uk
  introTitle: "**monofile** @ fyle.uk"
  introMessage: The open source, Discord-based file sharing service
  navbar:
    - title: Stable
      href: https://fyle.uk
    - title: Beta
      href: https://beta.fyle.uk
    - title: Mastodon
      href: https://so.fyle.uk

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
